#ifndef QUERYSVAR_H
#define QUERYSVAR_H

enum QUERYS { MODIFICARING, ANIADIRING, ANIADIRPLA, ANIADIRINGPLA, MODIFICARPLA};

enum ACTION { ACCEPT, DENY};

enum APARTADOS { PLATOS, INGREDIENTES , INGDEPLATO};

enum CHECKBOX { INCOMPATIBILIDADES, ALERGENOS};

#endif // QUERYSVAR_H
