#ifndef QUERYSVAR_H
#define QUERYSVAR_H

enum QUERYS { MOSTRARING, MOSTRARINFOING, ELIMINARING, MODIFICARING, ANIADIRING, MOSTRARPLA, MOSTRARINFOPLA, MOSTRARINGPLA, ANIADIRPLA, ANIADIRINGPLA, ELIMINARPLA, MODIFICARPLA};

enum ACTION { ACCEPT, DENY};

enum APARTADOS { PLATOS, INGREDIENTES , INGDEPLATO};

#endif // QUERYSVAR_H
